        <?php
error_reporting(0);
if(isset($_POST['submit'])){
    $message = $_POST['message'];
    if($message === ""){
        $message = "No Message";
    }
    $subject2 = $_POST['subject'];
    $email = $_POST['email'];
    $name = $_POST['name'];
    $mobile = $_POST['mobile'];
    $age = $_POST['age'];
    $occupation = $_POST['occupation'];
    $company= $_POST['company'];
    $position = $_POST['position'];
    $education = $_POST['education'];
    $address = $_POST['address'];
    $alma = $_POST['alma'];
$to = "amaaurangabad2015@gmail.com";  // AMA email here
    $subject = "AMA Website - Membership Form ".$subject2;
    $date = date_create();
        
    
    $body = "
    <br>
    <h3>Membership Form</h3><br>
    <b>Name : </b> {$name} 
    <br>
    <b>Email : </b> {$email} 
    <br>
    <b>Contact : </b>{$mobile}
    <br>
    <b>Age :</b>{$age}
    <br>
    <b>Occupation :</b> {$occupation}
    <br>
    <b>Company : </b>{$company}
    <br>
    <b>Position : </b>{$position}
    <br>
    <b>Education : </b>{$education}
    <br>
    <b>Address : </b>{$address}
    <br>
    <b>Alma Mater : </b>{$alma}
    <br>
    <b>Message : </b> {$message}<br>
    <b>Time : </b>". date_format($date, 'Y-m-d H:i:s')."
    <br>
    <h4>This message is generated by the AMA website.</h4>
    ";
    
    
include 'classes/class.phpmailer.php';
   $mail= new PHPMailer();
// comment isSMTP
 $mail->isSMTP();
   $mail->SMTPDebug=0;
   $mail->SMTPAuth=true;
   $mail->SMTPSecure='ssl';
   $mail->Host="smtp.gmail.com";
   $mail->Port=465;
   $mail->isHTML(true);
   $mail->Username="amasocial2@gmail.com";   // Add your Gmail Address.
   $mail->Password="amasocial@1";           
   $mail->setFrom("amasocial2@gmail.com");  // Add your Gmail Address.
   $mail->Subject=$subject;
   $mail->Body=$body;
   $mail->addAddress($to);
   if(!$mail->send())
   {
   	 echo "Mailer Error.".$mail->ErrorInfo;
   }
   else
   {
   	header("location:../contacted.html");
       echo "Message has been send Successfully!";
    
   }
}

?>


